version: '3'
networks:
  db-data-net:
    driver: bridge
services:
  todo-app:
    image: todo-app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=1234
    networks:
      - db-data-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:1.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
      tags:
        - "mysql:1.0"
    container_name: mysql

    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-data-net
volumes:
  db-data: